name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: src/.vuepress/dist
          external_repository: AltQ1231/altq1231.github.io
          publish_branch: main
          cname: altq1231.cn
          commit_message: ":rocket: deploy: "
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
